os:
  - linux
  
sudo: false

services:
  - docker

before_install:
  - docker pull jro7/flutter_lcov
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run jro7/flutter_lcov /bin/sh -c "cd /root/flutter_lcov; bundle exec rake test"

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      
before_script:
  - git clone https://github.com/flutter/flutter.git
  
script:
  - bundle exec rake test
  - ./flutter/bin/flutter analyze
  - ./flutter/bin/flutter test --coverage
cache:
  directories:
    - $HOME/.pub-cache
