name: widget_animator
description: Animate your widgets fast and easy
version: 1.0.0
author: dev-anton.engineer <dev.antonguinto@gmail.com>
homepage: https://github.com/antonvinceguinto/widget-animator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

