name: fast_listview_animation
description: Flutter package for easily implementing animations on how the items in the list appear
version: 0.0.1
author: Anton Vince Guinto <dev.antonguinto@gmail.com>
homepage: https://github.com/antonvinceguinto/fast-listview-animation

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

